apiVersion: v2
name: keycloak
description: Keycloak identity provider for CAIPE RBAC, token exchange, and identity federation
version: 0.5.67 # Do NOT bump this. It will be updated automatically using the PR or release workflow
appVersion: 0.5.67
type: application
