---
name: "[Lint] Conventional Commits"

on:
  push:
    # Run superlinter on pushes to default branch
    branches:
      - main
  # Run superlinter on pull request events
  pull_request:

# Declare default permissions as read-only
permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: 🔒 harden runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920  # v2.20.0
        with:
          egress-policy: audit
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
        with:
          fetch-depth: 0
      - name: 🧹 Conventional Commits
        uses: webiny/action-conventional-commits@7f91b1595ca1951cdb671ddc9f07a49081ec5b69 # v1.4.2
        with:
          allowed-commit-types: feat,fix,docs,style,refactor,test,build,perf,ci,chore,revert,merge,wip,bump,release
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}